'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { toast } from 'sonner'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Lock } from 'lucide-react'

/** Map DB key → i18n key under admin.settings.* */
const SETTING_I18N_KEY: Record<string, string> = {
  default_clock_in_time: 'defaultClockIn',
  default_clock_out_time: 'defaultClockOut',
  auto_clock_check_delay_minutes: 'autoClockCheckDelay',
  intern_missed_clock_alert_threshold: 'internMissedThreshold',
  fulltime_auto_clock_alert_days: 'fulltimeAutoAlertDays',
  overtime_min_advance_hours: 'overtimeMinAdvance',
  payroll_pay_day: 'payrollPayDay',
  payroll_auto_generate_day: 'payrollAutoGenerateDay',
  contract_reminder_days_first: 'contractReminderFirst',
  contract_reminder_days_second: 'contractReminderSecond',
  project_ot_coo_threshold_hours: 'projectOtCooThreshold',
}

interface Setting { key: string; value: string }

interface RoleSettingsSectionProps {
  title: string
  settings: Setting[]
  editable: boolean
}

export function RoleSettingsSection({ title, settings, editable }: RoleSettingsSectionProps) {
  const router = useRouter()
  const t = useTranslations('admin.settings')
  const tc = useTranslations('common')
  const [values, setValues] = useState<Record<string, string>>(
    Object.fromEntries(settings.map(s => [s.key, s.value ?? '']))
  )
  const [saving, setSaving] = useState<string | null>(null)

  const handleSave = async (key: string) => {
    setSaving(key)
    const res = await fetch('/api/admin/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key, value: values[key] }),
    })
    const { error } = await res.json()
    setSaving(null)
    if (error) { toast.error(error); return }
    toast.success(tc('saved'))
    router.refresh()
  }

  if (settings.length === 0) return null

  return (
    <div className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-hidden">
      <div className="px-5 py-3 bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700 flex items-center gap-2">
        <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300">{title}</h3>
        {!editable && <Lock size={13} className="text-slate-400" />}
      </div>
      <div className="divide-y divide-slate-100 dark:divide-slate-700">
        {settings.map(s => {
          const i18nKey = SETTING_I18N_KEY[s.key]
          const label = i18nKey ? t(i18nKey) : s.key
          return (
            <div key={s.key} className="px-5 py-3 flex items-center gap-3">
              <div className="flex-1 min-w-0">
                <p className="text-sm text-slate-700 dark:text-slate-300">{label}</p>
                <p className="text-xs text-slate-400 font-mono">{s.key}</p>
              </div>
              {editable ? (
                <>
                  <Input
                    value={values[s.key] ?? ''}
                    onChange={e => setValues(v => ({ ...v, [s.key]: e.target.value }))}
                    className="w-40 text-sm"
                    placeholder={t('inputPlaceholder', { label })}
                  />
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleSave(s.key)}
                    disabled={saving === s.key}
                  >
                    {saving === s.key ? tc('saving') : tc('save')}
                  </Button>
                </>
              ) : (
                <span className="text-sm text-slate-500 dark:text-slate-400 font-mono bg-slate-50 dark:bg-slate-700 px-3 py-1.5 rounded border border-slate-200 dark:border-slate-600 min-w-[100px] text-right">
                  {s.value || '—'}
                </span>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
