'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { toast } from 'sonner'
import { Save, PlugZap, CheckCircle2, XCircle } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { FEATURE_KEYS, type FeatureFlagKey } from '@/lib/feature-flag-keys'

const SENSITIVE_KEYS = ['teams_bot_secret', 'ai_api_key', 'ai_embed_api_key']

// AI 連線設定由專屬卡片渲染（不走通用欄位列表）
const AI_KEYS = ['ai_provider', 'ai_api_key', 'ai_base_url', 'ai_model', 'ai_last_test', 'ai_embed_base_url', 'ai_embed_api_key', 'ai_embed_model']

const AI_PROVIDERS = ['openai', 'anthropic', 'gemini', 'custom'] as const
const AI_DEFAULT_MODEL: Record<string, string> = {
  openai: 'gpt-4o-mini',
  anthropic: 'claude-haiku-4-5-20251001',
  gemini: 'gemini-1.5-flash',
  custom: '',
}

interface AiTestResult {
  ok: boolean; model?: string; ms?: number; error?: string; at: string
  embedOk?: boolean; embedModel?: string; embedMs?: number; embedError?: string
}

/** Map DB setting keys to i18n keys under admin.settings.* */
const SETTING_I18N_KEY: Record<string, string> = {
  default_clock_in_time: 'defaultClockIn',
  default_clock_out_time: 'defaultClockOut',
  auto_clock_check_delay_minutes: 'autoClockCheckDelay',
  intern_missed_clock_alert_threshold: 'internMissedThreshold',
  fulltime_auto_clock_alert_days: 'fulltimeAutoAlertDays',
  contract_reminder_days_first: 'contractReminderFirst',
  contract_reminder_days_second: 'contractReminderSecond',
  daily_digest_time: 'dailyDigestTime',
  teams_webhook_url: 'teamsWebhookUrl',
  teams_bot_id: 'teamsBotId',
  teams_bot_secret: 'teamsBotSecret',
  maintenance_mode: 'maintenanceMode',
  mfa_approval_session_minutes: 'mfaApprovalSession',
  overtime_min_advance_hours: 'overtimeMinAdvance',
  project_ot_coo_threshold_hours: 'projectOtCooThreshold',
  payroll_pay_day: 'payrollPayDay',
  payroll_auto_generate_day: 'payrollAutoGenerateDay',
}

interface Setting { key: string; value: string; description?: string; hasValue?: boolean }

interface Props {
  settings: Setting[]
  featureFlags: Record<string, boolean>
}

export function SettingsClient({ settings, featureFlags }: Props) {
  const router = useRouter()
  const t = useTranslations('admin.settings')
  const tn = useTranslations('nav')
  const tc = useTranslations('common')
  const [values, setValues] = useState<Record<string, string>>(
    Object.fromEntries(settings.map(s => [s.key, s.value ?? '']))
  )
  const [flags, setFlags] = useState<Record<string, boolean>>(featureFlags)
  const [saving, setSaving] = useState<string | null>(null)
  const [togglingFeature, setTogglingFeature] = useState<string | null>(null)
  const [aiTesting, setAiTesting] = useState(false)
  const [aiSaving, setAiSaving] = useState(false)
  const [aiLastTest, setAiLastTest] = useState<AiTestResult | null>(() => {
    try {
      const raw = settings.find(s => s.key === 'ai_last_test')?.value
      return raw ? (JSON.parse(raw) as AiTestResult) : null
    } catch { return null }
  })

  // 敏感值不在 client（server 只給 hasValue）：aiKeySet = 已存有值或本次已輸入新值
  const savedKeyFlags = Object.fromEntries(settings.filter(s => s.hasValue !== undefined).map(s => [s.key, s.hasValue as boolean]))
  const aiProvider = values['ai_provider'] || 'gemini'
  const aiKeySet = !!(values['ai_api_key'] ?? '').trim() || !!savedKeyFlags['ai_api_key']
  const embedModelSet = !!(values['ai_embed_model'] ?? '').trim()
  const [reindexing, setReindexing] = useState(false)

  const handleReindex = async () => {
    setReindexing(true)
    const res = await fetch('/api/admin/settings/reindex-docs', { method: 'POST' })
    const { data, error } = await res.json()
    setReindexing(false)
    if (error) { toast.error(error); return }
    toast.success(t('aiReindexDone', { docs: data.docs, chunks: data.chunks }))
  }

  const handleSaveAi = async () => {
    setAiSaving(true)
    for (const key of ['ai_provider', 'ai_api_key', 'ai_base_url', 'ai_model', 'ai_embed_base_url', 'ai_embed_api_key', 'ai_embed_model']) {
      // 敏感 key：空值＝未輸入新值 → 不覆寫既有的 key（要更換就輸入新值）
      if (SENSITIVE_KEYS.includes(key) && !(values[key] ?? '').trim() && savedKeyFlags[key]) continue
      const res = await fetch('/api/admin/settings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ key, value: values[key] ?? '' }),
      })
      const { error } = await res.json()
      if (error) { toast.error(error); setAiSaving(false); return }
    }
    setAiSaving(false)
    toast.success(tc('saved'))
    router.refresh()
  }

  const handleTestAi = async () => {
    setAiTesting(true)
    const res = await fetch('/api/admin/settings/ai-test', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        provider: values['ai_provider'],
        api_key: values['ai_api_key'],
        base_url: values['ai_base_url'],
        model: values['ai_model'],
        embed_base_url: values['ai_embed_base_url'],
        embed_api_key: values['ai_embed_api_key'],
        embed_model: values['ai_embed_model'],
      }),
    })
    const { data, error } = await res.json()
    setAiTesting(false)
    if (error) { toast.error(error); return }
    setAiLastTest(data)
  }

  const formatTestTime = (iso: string) =>
    new Date(iso).toLocaleString('zh-TW', { timeZone: 'Asia/Taipei', hour12: false })

  const handleSave = async (key: string) => {
    // 敏感 key：空值＝未輸入新值 → 不覆寫既有值
    if (SENSITIVE_KEYS.includes(key) && !(values[key] ?? '').trim() && savedKeyFlags[key]) {
      toast.error(t('secretSetPlaceholder'))
      return
    }
    setSaving(key)
    const res = await fetch('/api/admin/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key, value: values[key] }),
    })
    const { error } = await res.json()
    setSaving(null)
    if (error) { toast.error(error); return }
    toast.success(tc('saved'))
    router.refresh()
  }

  const handleToggleFeature = async (feature: FeatureFlagKey) => {
    const newVal = !flags[feature]
    setTogglingFeature(feature)
    const res = await fetch('/api/admin/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: `feature.${feature}`, value: String(newVal) }),
    })
    const { error } = await res.json()
    setTogglingFeature(null)
    if (error) { toast.error(error); return }
    setFlags(f => ({ ...f, [feature]: newVal }))
    toast.success(tc('saved'))
    router.refresh()
  }

  const FEATURE_NAV_KEY: Record<FeatureFlagKey, string> = {
    attendance: 'attendance',
    leave: 'leave',
    overtime: 'overtime',
    payroll: 'payroll',
    documents: 'documents',
    announcements: 'announcements',
    contracts: 'contracts',
    projects: 'projects',
    feedback: 'feedback',
    procurement: 'procurement',
    daily_report: 'dailyReport',
    expenses: 'expenses',
    approvals: 'approvals',
    assets: 'assets',
    training: 'training',
    business_trip: 'businessTrip',
    calendar: 'calendar',
    insights: 'insights',
    ask_ai: 'askAi',
    lifecycle: 'lifecycle',
    recruiting: 'recruiting',
    lab_supplies: 'labSupplies',
    performance: 'performance',
  }

  const generalSettings = settings.filter(s => !AI_KEYS.includes(s.key))

  const groupDefs: [string, (key: string) => boolean][] = [
    [t('groupClock'), k => k.includes('clock') || k.includes('intern_missed') || k.includes('fulltime_auto')],
    [t('groupNotification'), k => k.includes('contract_reminder') || k.includes('daily_digest') || k.includes('teams_')],
    [t('groupSystem'), k => ['maintenance_mode', 'mfa_approval_session_minutes', 'overtime_min_advance_hours', 'project_ot_coo_threshold_hours', 'payroll_pay_day', 'payroll_auto_generate_day'].includes(k)],
  ]
  const grouped = new Set<string>()
  const groups: Record<string, Setting[]> = {}
  for (const [name, matcher] of groupDefs) {
    groups[name] = generalSettings.filter(s => {
      if (matcher(s.key)) { grouped.add(s.key); return true }
      return false
    })
  }
  const ungrouped = generalSettings.filter(s => !grouped.has(s.key))
  if (ungrouped.length > 0) groups[t('groupOther')] = ungrouped

  const aiStatusRows: { label: string; ok: boolean; note: string }[] = [
    { label: t('aiStatusTranslate'), ok: aiKeySet, note: aiKeySet ? t('aiStatusReady') : t('aiStatusNoKey') },
    {
      label: t('aiStatusAskAi'),
      ok: aiKeySet && !!flags.ask_ai,
      note: !aiKeySet ? t('aiStatusNoKey') : !flags.ask_ai ? t('aiStatusFlagOff') : t('aiStatusReady'),
    },
    { label: t('aiStatusOcr'), ok: aiKeySet, note: aiKeySet ? t('aiStatusReady') : t('aiStatusNoKey') },
    {
      label: t('aiStatusVector'),
      ok: aiKeySet && embedModelSet,
      note: !aiKeySet ? t('aiStatusNoKey') : embedModelSet ? t('aiStatusReady') : t('aiStatusNoEmbedModel'),
    },
  ]

  return (
    <div className="space-y-6 max-w-2xl">
      {/* Feature flags section */}
      <div className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-hidden">
        <div className="px-5 py-3 bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700">
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300">{t('groupFeatures')}</h3>
          <p className="text-xs text-slate-400 mt-0.5">{t('groupFeaturesDesc')}</p>
        </div>
        <div className="divide-y divide-slate-100 dark:divide-slate-700">
          {FEATURE_KEYS.map(feature => {
            const enabled = flags[feature] ?? false
            const isToggling = togglingFeature === feature
            return (
              <div key={feature} className="px-5 py-3 flex items-center justify-between gap-4">
                <div>
                  <p className="text-sm font-medium text-slate-700 dark:text-slate-300">
                    {tn(FEATURE_NAV_KEY[feature])}
                  </p>
                  <p className="text-xs text-slate-400">/{feature}</p>
                </div>
                <button
                  onClick={() => handleToggleFeature(feature)}
                  disabled={isToggling}
                  className={[
                    'relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none shrink-0',
                    enabled
                      ? 'bg-blue-600 dark:bg-blue-500'
                      : 'bg-slate-200 dark:bg-slate-600',
                    isToggling ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer',
                  ].join(' ')}
                  aria-label={enabled ? t('featureDisable') : t('featureEnable')}
                >
                  <span
                    className={[
                      'inline-block h-4 w-4 transform rounded-full bg-white shadow transition-transform',
                      enabled ? 'translate-x-6' : 'translate-x-1',
                    ].join(' ')}
                  />
                </button>
              </div>
            )
          })}
        </div>
      </div>

      {/* AI 連線（翻譯 / 政策問答 / OCR 共用） */}
      <div className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-hidden">
        <div className="px-5 py-3 bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700">
          <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300">{t('aiConnTitle')}</h3>
          <p className="text-xs text-slate-400 mt-0.5">{t('aiConnDesc')}</p>
        </div>
        <div className="px-5 py-4 space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">{t('aiProvider')}</label>
              <Select value={aiProvider} onValueChange={v => setValues(s => ({ ...s, ai_provider: v ?? 'gemini' }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {AI_PROVIDERS.map(p => (
                    <SelectItem key={p} value={p}>
                      {p === 'openai' ? 'OpenAI' : p === 'anthropic' ? 'Anthropic' : p === 'gemini' ? 'Google Gemini' : t('aiProviderCustom')}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div>
              <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">{t('aiModel')}</label>
              <Input
                value={values['ai_model'] ?? ''}
                onChange={e => setValues(s => ({ ...s, ai_model: e.target.value }))}
                placeholder={AI_DEFAULT_MODEL[aiProvider] || t('aiModelCustomPlaceholder')}
              />
            </div>
          </div>
          <div>
            <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">{t('aiApiKey')}</label>
            {/* 真實 key 不會下到前端（server 只給 hasValue）；要更換就輸入新值 */}
            <Input
              type="password"
              value={values['ai_api_key'] ?? ''}
              onChange={e => setValues(s => ({ ...s, ai_api_key: e.target.value }))}
              placeholder={savedKeyFlags['ai_api_key'] ? t('secretSetPlaceholder') : t('secretUnsetPlaceholder')}
            />
          </div>
          {aiProvider === 'custom' && (
            <div>
              <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">{t('aiBaseUrl')}</label>
              <Input
                value={values['ai_base_url'] ?? ''}
                onChange={e => setValues(s => ({ ...s, ai_base_url: e.target.value }))}
                placeholder="https://your-endpoint.example.com"
              />
            </div>
          )}

          {/* Embedding（向量檢索）：URL/Key 留空沿用上方 AI 連線；model 必填才啟用 */}
          <div className="pt-3 border-t border-slate-100 dark:border-slate-700">
            <p className="text-sm font-medium text-slate-700 dark:text-slate-300">{t('aiEmbedTitle')}</p>
            <p className="text-xs text-slate-400 mt-0.5 mb-3">{t('aiEmbedHint')}</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label className="text-xs font-medium text-slate-500 dark:text-slate-400 block mb-1">{t('aiEmbedModel')}</label>
                <Input
                  value={values['ai_embed_model'] ?? ''}
                  onChange={e => setValues(s => ({ ...s, ai_embed_model: e.target.value }))}
                  placeholder="text-embedding-3-small / text-embedding-004 / …"
                />
              </div>
              <div>
                <label className="text-xs font-medium text-slate-500 dark:text-slate-400 block mb-1">{t('aiEmbedBaseUrl')}</label>
                <Input
                  value={values['ai_embed_base_url'] ?? ''}
                  onChange={e => setValues(s => ({ ...s, ai_embed_base_url: e.target.value }))}
                  placeholder={t('aiEmbedInherit')}
                />
              </div>
              <div className="sm:col-span-2">
                <label className="text-xs font-medium text-slate-500 dark:text-slate-400 block mb-1">{t('aiEmbedApiKey')}</label>
                <Input
                  type="password"
                  value={values['ai_embed_api_key'] ?? ''}
                  onChange={e => setValues(s => ({ ...s, ai_embed_api_key: e.target.value }))}
                  placeholder={savedKeyFlags['ai_embed_api_key'] ? t('secretSetPlaceholder') : t('aiEmbedInherit')}
                />
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <Button size="sm" className="min-h-[36px]" onClick={handleSaveAi} disabled={aiSaving}>
              <Save size={13} className="mr-1" />{aiSaving ? tc('saving') : tc('save')}
            </Button>
            <Button size="sm" variant="outline" className="min-h-[36px]" onClick={handleTestAi} disabled={aiTesting}>
              <PlugZap size={13} className="mr-1" />{aiTesting ? t('aiTesting') : t('aiTest')}
            </Button>
            {embedModelSet && (
              <Button size="sm" variant="outline" className="min-h-[36px]" onClick={handleReindex} disabled={reindexing}>
                {reindexing ? t('aiReindexing') : t('aiReindex')}
              </Button>
            )}
          </div>
          {aiLastTest && (
            <div className="space-y-1">
              <p className={`inline-flex items-center gap-1 text-xs ${aiLastTest.ok ? 'text-green-600 dark:text-green-400' : 'text-red-500 dark:text-red-400'}`}>
                {aiLastTest.ok
                  ? <><CheckCircle2 size={13} /> {t('aiTestOk', { model: aiLastTest.model ?? '', ms: aiLastTest.ms ?? 0 })}</>
                  : <><XCircle size={13} /> {t('aiTestFail', { error: aiLastTest.error ?? '' })}</>}
                <span className="text-slate-400">· {formatTestTime(aiLastTest.at)}</span>
              </p>
              {aiLastTest.embedOk !== undefined && (
                <p className={`flex items-center gap-1 text-xs ${aiLastTest.embedOk ? 'text-green-600 dark:text-green-400' : 'text-red-500 dark:text-red-400'}`}>
                  {aiLastTest.embedOk
                    ? <><CheckCircle2 size={13} /> {t('aiTestEmbedOk', { model: aiLastTest.embedModel ?? '', ms: aiLastTest.embedMs ?? 0 })}</>
                    : <><XCircle size={13} /> {t('aiTestEmbedFail', { error: aiLastTest.embedError ?? '' })}</>}
                </p>
              )}
            </div>
          )}
          {/* 功能狀態一覽 */}
          <div className="rounded-md border border-slate-100 dark:border-slate-700 divide-y divide-slate-100 dark:divide-slate-700">
            {aiStatusRows.map(row => (
              <div key={row.label} className="px-3 py-2 flex items-center justify-between text-sm">
                <span className="text-slate-600 dark:text-slate-300">{row.label}</span>
                <span className={`text-xs inline-flex items-center gap-1 ${row.ok ? 'text-green-600 dark:text-green-400' : 'text-amber-500'}`}>
                  {row.ok ? <CheckCircle2 size={12} /> : <XCircle size={12} />}{row.note}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Regular settings groups */}
      {Object.entries(groups).map(([groupName, groupSettings]) => {
        if (groupSettings.length === 0) return null
        return (
          <div key={groupName} className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-hidden">
            <div className="px-5 py-3 bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700">
              <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300">{groupName}</h3>
            </div>
            <div className="divide-y divide-slate-100 dark:divide-slate-700">
              {groupSettings.map(setting => {
                // 敏感值不在 client（server 只給 hasValue）：password 欄 + 「已設定」placeholder，輸入新值即可更換
                const isSensitive = SENSITIVE_KEYS.includes(setting.key)
                const i18nKey = SETTING_I18N_KEY[setting.key]
                const label = i18nKey ? t(i18nKey) : setting.key
                const currentVal = values[setting.key] ?? ''

                return (
                  <div key={setting.key} className="px-5 py-4">
                    <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">
                      {label}
                    </label>
                    {setting.description && (
                      <p className="text-xs text-slate-400 mb-2">{setting.description}</p>
                    )}
                    <div className="flex items-center gap-2">
                      <div className="relative flex-1">
                        <Input
                          type={isSensitive ? 'password' : 'text'}
                          value={currentVal}
                          onChange={e => setValues(v => ({ ...v, [setting.key]: e.target.value }))}
                          placeholder={isSensitive
                            ? (setting.hasValue ? t('secretSetPlaceholder') : t('secretUnsetPlaceholder'))
                            : t('inputPlaceholder', { label })}
                        />
                      </div>
                      <Button
                        size="sm"
                        variant="outline"
                        className="min-h-[36px] shrink-0"
                        onClick={() => handleSave(setting.key)}
                        disabled={saving === setting.key}
                      >
                        <Save size={13} className="mr-1" />
                        {saving === setting.key ? tc('saving') : tc('save')}
                      </Button>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )
      })}
    </div>
  )
}
