'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { toast } from 'sonner'
import { Eye, EyeOff, Save } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'

const SENSITIVE_KEYS = ['gemini_api_key', 'teams_bot_secret']

/** Map DB setting keys to i18n keys under admin.settings.* */
const SETTING_I18N_KEY: Record<string, string> = {
  gemini_api_key: 'geminiApiKey',
  default_clock_in_time: 'defaultClockIn',
  default_clock_out_time: 'defaultClockOut',
  auto_clock_check_delay_minutes: 'autoClockCheckDelay',
  intern_missed_clock_alert_threshold: 'internMissedThreshold',
  fulltime_auto_clock_alert_days: 'fulltimeAutoAlertDays',
  contract_reminder_days_first: 'contractReminderFirst',
  contract_reminder_days_second: 'contractReminderSecond',
  daily_digest_time: 'dailyDigestTime',
  teams_webhook_url: 'teamsWebhookUrl',
  teams_bot_id: 'teamsBotId',
  teams_bot_secret: 'teamsBotSecret',
  maintenance_mode: 'maintenanceMode',
  mfa_approval_session_minutes: 'mfaApprovalSession',
  overtime_min_advance_hours: 'overtimeMinAdvance',
  project_ot_coo_threshold_hours: 'projectOtCooThreshold',
  payroll_pay_day: 'payrollPayDay',
  payroll_auto_generate_day: 'payrollAutoGenerateDay',
}

interface Setting { key: string; value: string; description?: string }

export function SettingsClient({ settings }: { settings: Setting[] }) {
  const router = useRouter()
  const t = useTranslations('admin.settings')
  const tc = useTranslations('common')
  const [values, setValues] = useState<Record<string, string>>(
    Object.fromEntries(settings.map(s => [s.key, s.value ?? '']))
  )
  const [showKeys, setShowKeys] = useState<Record<string, boolean>>({})
  const [saving, setSaving] = useState<string | null>(null)

  const handleSave = async (key: string) => {
    setSaving(key)
    const res = await fetch('/api/admin/settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key, value: values[key] }),
    })
    const { error } = await res.json()
    setSaving(null)
    if (error) { toast.error(error); return }
    toast.success(tc('saved'))
    router.refresh()
  }

  const groupDefs: [string, (key: string) => boolean][] = [
    [t('groupAi'), k => k.includes('gemini')],
    [t('groupClock'), k => k.includes('clock') || k.includes('intern_missed') || k.includes('fulltime_auto')],
    [t('groupNotification'), k => k.includes('contract_reminder') || k.includes('daily_digest') || k.includes('teams_')],
    [t('groupSystem'), k => ['maintenance_mode', 'mfa_approval_session_minutes', 'overtime_min_advance_hours', 'project_ot_coo_threshold_hours', 'payroll_pay_day', 'payroll_auto_generate_day'].includes(k)],
  ]
  const grouped = new Set<string>()
  const groups: Record<string, Setting[]> = {}
  for (const [name, matcher] of groupDefs) {
    groups[name] = settings.filter(s => {
      if (matcher(s.key)) { grouped.add(s.key); return true }
      return false
    })
  }
  // Catch-all for any settings not in a group
  const ungrouped = settings.filter(s => !grouped.has(s.key))
  if (ungrouped.length > 0) groups[t('groupOther')] = ungrouped

  return (
    <div className="space-y-6 max-w-2xl">
      {Object.entries(groups).map(([groupName, groupSettings]) => {
        if (groupSettings.length === 0) return null
        return (
          <div key={groupName} className="rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 overflow-hidden">
            <div className="px-5 py-3 bg-slate-50 dark:bg-slate-700/50 border-b border-slate-200 dark:border-slate-700">
              <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300">{groupName}</h3>
            </div>
            <div className="divide-y divide-slate-100 dark:divide-slate-700">
              {groupSettings.map(setting => {
                const isSensitive = SENSITIVE_KEYS.includes(setting.key)
                const showValue = showKeys[setting.key]
                const i18nKey = SETTING_I18N_KEY[setting.key]
                const label = i18nKey ? t(i18nKey) : setting.key
                const currentVal = values[setting.key] ?? ''
                const displayVal = isSensitive && !showValue && currentVal
                  ? '•'.repeat(Math.min(currentVal.length, 24))
                  : currentVal

                return (
                  <div key={setting.key} className="px-5 py-4">
                    <label className="text-sm font-medium text-slate-700 dark:text-slate-300 block mb-1.5">
                      {label}
                    </label>
                    {setting.description && (
                      <p className="text-xs text-slate-400 mb-2">{setting.description}</p>
                    )}
                    <div className="flex items-center gap-2">
                      <div className="relative flex-1">
                        <Input
                          type={isSensitive && !showValue ? 'password' : 'text'}
                          value={isSensitive && !showValue ? displayVal : currentVal}
                          onChange={e => !(!showValue && isSensitive) && setValues(v => ({ ...v, [setting.key]: e.target.value }))}
                          onFocus={() => isSensitive && setShowKeys(k => ({ ...k, [setting.key]: true }))}
                          className="pr-10"
                          placeholder={t('inputPlaceholder', { label })}
                        />
                        {isSensitive && (
                          <button
                            type="button"
                            onClick={() => setShowKeys(k => ({ ...k, [setting.key]: !k[setting.key] }))}
                            className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                          >
                            {showValue ? <EyeOff size={15} /> : <Eye size={15} />}
                          </button>
                        )}
                      </div>
                      <Button
                        size="sm"
                        variant="outline"
                        className="min-h-[36px] shrink-0"
                        onClick={() => handleSave(setting.key)}
                        disabled={saving === setting.key}
                      >
                        <Save size={13} className="mr-1" />
                        {saving === setting.key ? tc('saving') : tc('save')}
                      </Button>
                    </div>
                  </div>
                )
              })}
            </div>
          </div>
        )
      })}
    </div>
  )
}
